[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'habamax/vim-asciidoctor'
on_ft = ['asciidoc']
hook_add = 'execute "source " . g:dein_base_dir . "/rc/asciidoctor.vim"'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_add = 'execute "source " . g:dein_base_dir . "/rc/markdown.vim"'

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown']
hook_add = 'execute "source " . g:dein_base_dir . "/rc/markdown-quote-syntax.vim"'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'markdown']
hook_add = 'execute "source " . g:dein_base_dir . "/rc/emmet.vim"'

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_add = 'execute "source " . g:dein_base_dir . "/rc/rust.vim"'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rust']
