[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1
hook_add = 'execute "source " . g:dein_base_dir . "/rc/neocomplete.vim"'

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
hook_add = 'execute "source " . g:dein_base_dir . "/rc/neosnippet.vim"'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1
on_ft = 'snippet'
