[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = 'execute "source " . g:dein_base_dir . "/rc/deoplete.vim"'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
hook_add = 'execute "source " . g:dein_base_dir . "/rc/neosnippet.vim"'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = ['rust']
hook_add = 'execute "source " . g:dein_base_dir . "/rc/deoplete-rust.vim"'
depends = 'deoplete.nvim'
